# Generated by Django 5.2.3 on 2025-07-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollno", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("marks", models.IntegerField()),
                ("add", models.CharField(max_length=50)),
            ],
        ),
    ]
